# Generated by Django 5.2.3 on 2025-06-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_groupmembers_options_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Rent', 'Rent'), ('Bills', 'Bills'), ('Groceries', 'Groceries'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Gifts', 'Gifts'), ('General', 'General')], default='General', max_length=20),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
